FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependency files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

# Non-root user
RUN chown -R node:node /app
USER node

EXPOSE 3000

# Use Dumb-init or just node. 
CMD ["node", "dist/index.js"]
