version: '3.8'

services:
  # Instância de Persistência PostgreSQL
  db:
    image: postgres:15.6-alpine
    container_name: portfolio_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - network_aplicacao

  # Instância de Cache Redis
  redis:
    image: redis:7.2-alpine
    container_name: showcase_cache
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_aplicacao

  # Fastify API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: show_fastify_backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@db:5432/${PG_DB}
      REDIS_HOST: redis
    networks:
      - network_borda
      - network_aplicacao
    depends_on:
      - db
      - redis

  # Servidor de Borda (Reverse Proxy)
  caddy:
    image: caddy:2.7.6-alpine
    container_name: show_caddy_reverse
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - network_borda
    depends_on:
      - backend

volumes:
  pg_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  network_borda:
    driver: bridge
  network_aplicacao:
    driver: bridge
    internal: true
